### ISSUE TITLE
uninstall fedora not work

### ISSUE THREAD

**Issue by wangmu0579** [nmilosev/termux-fedora#15]
Could you help?
I tried install xkde-desktop but seems the file size so big. So i try to uninstall the whole fedora:
And got many error with 
rm: cannot remove '/data/data/com.termux/files/home/fedora/usr/lib/fontconfig': Permission denied                             rm: cannot remove '/data/data/com.termux/files/home/fedora/usr/lib/modprobe.d': Permission denied                             rm: cannot remove '/data/data/com.termux/files/home/fedora/usr/lib/python2.7': Permission denied                              rm: cannot remove '/data/data/com.termux/files/home/fedora/usr/lib/qt5': Permission denied
....
.

**Comment by nmilosev** [comment]
This sometimes happens due to proot creating files with fake-root option.

I would recommend go to Android settings -> Apps -> Termux and clearing the data. Be careful, because this will remove anything you have inside the Termux home directory. It will be just as like you reinstalled Termux.

On a side note use ```dnf install @xfce``` or ```dnf install @lxde``` instead of ```dnf install xfce-desktop```, that way the space needed will be lower because you only get the most necessary packages.

**Comment by wangmu0579** [comment]
Great thanks for your help.

**Comment by nmilosev** [comment]
Sure! :) Let me know if you have any other issues. For running graphical applications I now usually just install openbox, as it is very small and enough to run whatever you need.

**Comment by wangmu0579** [comment]
I have met a new problem. 
Now I installed the  @lxde and  can get GUI from XSDL Xserver in android. 
Do we have way connect lxde from the remote computer?
I installed the xrdp server in Fedora and using Windows RDP client. But I blocked at input the user/password.
Will try to search the openBox.

**Comment by nmilosev** [comment]
I would try setting up `tigervnc`.
